import { test, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';

test('real museum collection renders on desktop and mobile', async ({ page }) => {
  test.setTimeout(90000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await mkdir('test-results/visual', { recursive: true });
  await page.setViewportSize({ width: 1280, height: 960 });
  await page.goto('/cs409-mp2/gallery');
  await expect.poll(() => page.getByTestId('artwork').count()).toBeGreaterThan(12);
  await expect(page.getByText('Museum API connected', { exact: true })).toBeVisible({ timeout: 45000 });
  await expect.poll(() => page.locator('.art-card img').first().evaluate(image => (image as HTMLImageElement).naturalWidth), { timeout: 20000 }).toBeGreaterThan(1);
  await page.screenshot({ path: 'test-results/visual/gallery-desktop.png' });
  await page.getByTestId('artwork').first().getByRole('link').click();
  await expect(page.getByTestId('detail')).toBeVisible();
  await expect.poll(() => page.locator('.detail-figure img').evaluate(image => (image as HTMLImageElement).naturalWidth), { timeout: 20000 }).toBeGreaterThan(1);
  await page.screenshot({ path: 'test-results/visual/detail-desktop.png', fullPage: true });
  await page.reload();
  await expect(page.getByTestId('detail')).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/visual/detail-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.goto('/cs409-mp2/list');
  await expect(page.getByTestId('artwork').first()).toBeVisible();
  await page.screenshot({ path: 'test-results/visual/list-mobile.png' });
  await page.setViewportSize({ width: 1280, height: 960 });
  await page.screenshot({ path: 'test-results/visual/list-desktop.png' });
  expect(errors).toEqual([]);
});
